---
- name: Create Nginx site directory
  file:
    path: "{{ nginx_app_dir }}"
    state: directory
    mode: '0755'

- name: Copy static site files
  copy:
    src: index.html
    dest: "{{ nginx_app_dir }}/index.html"
    mode: '0644'
    force: yes

- name: Run nginx container
  community.docker.docker_container:
    name: "{{ nginx_container_name }}"
    image: nginx:alpine
    state: started
    restart_policy: always
    ports:
      - "8080:80"
    volumes:
      - "{{ nginx_app_dir }}:/usr/share/nginx/html:ro"
