---
- name: Deploy Node.js app
  block:
  - name: Create node.js app directory
    file:
      path: "{{ nodejs_app_dir }}"
      state: directory
      mode: '0755'

  - name: Copy node.js app files
    copy:
      src: "{{ item }}"
      dest: "{{ nodejs_app_dir }}/{{ item }}"
      mode: '0644'
    loop:
      - app.js
      - package.json
      - Dockerfile

  - name: Build node.js Docker image
    community.docker.docker_image:
      name: "{{ nodejs_app_name }}"
      build:
        path: "{{ nodejs_app_dir }}"
      source: build
      state: present

  - name: Run Node.js container
    community.docker.docker_container:
      name: "{{ nodejs_container_name }}"
      image: "{{ nodejs_app_name }}"
      state: started
      restart_policy: always
      ports:
        - "3000:3000"

  - name: Wait for node.js app to be ready
    wait_for:
      host: localhost
      port: 3000
      delay: 3
      timeout: 30
      msg: "Node.js app did not start on port 3000"

  - name: Check node.js app is responding
    uri:
      url: "http://localhost:3000"
      method: GET
      status_code: 200
    register: nodejs_health
    retries: 3
    delay: 3

  - name: Node.js check result
    debug:
      msg: "Node.js is UP - responded with HTTP {{ nodejs_health.status }}"

  - name: Set Node.js status success
    set_fact:
      nodejs_status: "UP - http://localhost:3000"

  rescue:
    - name: Node.js deploymend failed
      debug:
        msg: >
          Node.js deployment failed!
          Check app.js and package.json in {{ nodejs_app_dir }}.

    - name: Set Node.js status failed
      set_fact:
        nodejs_status: "FAILED"      

  always:
    - name: Node.js deploy status
      debug:
        msg: "Node.js role finished - status {{ nodejs_status }}."


